#!/bin/bash
# initialize.sh — Initialize all contracts and wire dependencies.
#
# Reads contract IDs from .deployed.json (created by deploy.sh).
# Must be run after deploy.sh.
#
# Usage: ./scripts/initialize.sh

set -euo pipefail

NETWORK="testnet"
SOURCE="priya"

# ── Load deployment ───────────────────────────────────────────────────────────
if [ ! -f .deployed.json ]; then
    echo "❌ .deployed.json not found. Run ./scripts/deploy.sh first."
    exit 1
fi

PRICING_ID=$(jq -r '.pricingEngine' .deployed.json)
VAULT_ID=$(jq -r '.vault' .deployed.json)
MARKET_ID=$(jq -r '.optionMarket' .deployed.json)
ORACLE_ID=$(jq -r '.mockOracle' .deployed.json)

echo "======================================================"
echo "   Strix Protocol — Contract Initialization"
echo "======================================================"
echo "   PricingEngine : $PRICING_ID"
echo "   Vault         : $VAULT_ID"
echo "   OptionMarket  : $MARKET_ID"
echo "   MockOracle    : $ORACLE_ID"
echo ""

# ── Get admin address ──────────────────────────────────────────────────────────
ADMIN_ADDR=$(stellar keys address "$SOURCE")
echo "   Admin : $ADMIN_ADDR"
echo ""

# ── Testnet USDC ──────────────────────────────────────────────────────────────
# SAC-wrapped USDC on testnet (Circle's test USDC)
USDC_ID="CBIELTK6YBZJU5UP2WWQEUCYKLPU6AUNZ2BQ4WWFEIE3USCIHMXQDAMA"

echo "   USDC  : $USDC_ID"
echo ""

# ── Initialize MockOracle ─────────────────────────────────────────────────────
# Price: 0.12 USDC per XLM = 12_000_000_000_000 in 14-decimal
# (14-decimal: 1 USDC = 10^14; 7-decimal: 1 USDC = 10^7)
echo "⚙️  Initializing MockOracle (0.12 USDC/XLM)..."
stellar contract invoke \
    --id "$ORACLE_ID" \
    --source "$SOURCE" \
    --network "$NETWORK" \
    -- initialize \
    --admin "$ADMIN_ADDR" \
    --initial_price_14dec 12000000000000
echo "   ✅ MockOracle initialized (XLM = 0.12 USDC)"

# ── Initialize PricingEngine ──────────────────────────────────────────────────
echo "⚙️  Initializing PricingEngine..."
stellar contract invoke \
    --id "$PRICING_ID" \
    --source "$SOURCE" \
    --network "$NETWORK" \
    -- initialize \
    --admin "$ADMIN_ADDR" \
    --oracle "$ORACLE_ID" \
    --iv_bps 8000 \
    --spread_bps 100
echo "   ✅ PricingEngine initialized (IV=80%, spread=1%)"

# ── Initialize UnderwritingVault ──────────────────────────────────────────────
echo "⚙️  Initializing UnderwritingVault..."
# max_tvl = 1,000,000 USDC = 10_000_000_000_000 (7-decimal)
stellar contract invoke \
    --id "$VAULT_ID" \
    --source "$SOURCE" \
    --network "$NETWORK" \
    -- initialize \
    --admin "$ADMIN_ADDR" \
    --usdc_token "$USDC_ID" \
    --max_tvl 10000000000000
echo "   ✅ UnderwritingVault initialized (maxTVL=1M USDC)"

# ── Set option_market on vault ─────────────────────────────────────────────────
echo "⚙️  Wiring OptionMarket → Vault..."
stellar contract invoke \
    --id "$VAULT_ID" \
    --source "$SOURCE" \
    --network "$NETWORK" \
    -- set_option_market \
    --admin "$ADMIN_ADDR" \
    --option_market "$MARKET_ID"
echo "   ✅ Vault wired to OptionMarket"

# ── Initialize OptionMarket ───────────────────────────────────────────────────
echo "⚙️  Initializing OptionMarket..."
# contract_size = 1 XLM = 10_000_000 (7-decimal)
stellar contract invoke \
    --id "$MARKET_ID" \
    --source "$SOURCE" \
    --network "$NETWORK" \
    -- initialize \
    --admin "$ADMIN_ADDR" \
    --pricing_engine "$PRICING_ID" \
    --vault "$VAULT_ID" \
    --usdc_token "$USDC_ID" \
    --oracle "$ORACLE_ID" \
    --contract_size 10000000
echo "   ✅ OptionMarket initialized"

# ── Save env file ──────────────────────────────────────────────────────────────
cat > .env.testnet <<EOF
# Auto-generated by initialize.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
PRICING_ENGINE_ID=$PRICING_ID
VAULT_ID=$VAULT_ID
OPTION_MARKET_ID=$MARKET_ID
ORACLE_ID=$ORACLE_ID
USDC_ID=$USDC_ID
ADMIN_ADDRESS=$ADMIN_ADDR
EOF

echo ""
echo "======================================================"
echo "✅ All contracts initialized and wired!"
echo "   Environment saved to .env.testnet"
echo ""
echo "ℹ️  Oracle price can be updated with:"
echo "   stellar contract invoke --id $ORACLE_ID --source $SOURCE --network $NETWORK"
echo "     -- set_price --admin $ADMIN_ADDR --price_14dec <NEW_PRICE>"
echo ""
echo "▶  Next step: ./scripts/seed-vault.sh"
echo "======================================================"
