export interface CommunityAccount {
  name:      string;
  handle:    string;
  role:      string;
  location:  string;
  bio:       string;
  initials:  string;
  publicKey: string;
}

export const COMMUNITY_ACCOUNTS: CommunityAccount[] = [
  {
    name:      'Rohan Sharma',
    handle:    'rohan_s',
    role:      'Options Trader',
    location:  'Bangalore, IN',
    bio:       'SDE-2 by day, DeFi degenerate by night. Trades vol across protocols — found Strix through the Stellar Discord.',
    initials:  'RS',
    publicKey: 'GCSM3UOWL2H27WV6F63J6INHVYUKNRDHCRDZKVAW3NU6FNRQSZNNLGSW',
  },
  {
    name:      'Ananya Iyer',
    handle:    'ananyai',
    role:      'Liquidity Provider',
    location:  'Chennai, IN',
    bio:       'Into passive yield strategies. Allocates a portion of her crypto portfolio to DeFi vaults every month.',
    initials:  'AI',
    publicKey: 'GBMNYAW4EVLJEPI4SXNAIIW7R3XOCMRM5WMILW7MTIBADKS37SDHPGP4',
  },
  {
    name:      'Karan Malhotra',
    handle:    'karan_m',
    role:      'Market Maker',
    location:  'Delhi, IN',
    bio:       'Runs market-making scripts on a few Stellar DEX pairs. Here to see how on-chain options liquidity behaves.',
    initials:  'KM',
    publicKey: 'GCZLB4XUSS3A2K7Z6Y6D6P53EYLKDLAXWBTICCDYEPXRYOS2MAJRV2C2',
  },
  {
    name:      'Dev Patel',
    handle:    'devp_xyz',
    role:      'Arbitrageur',
    location:  'Ahmedabad, IN',
    bio:       'Blockchain developer with a thing for price inefficiencies. Monitors multiple Stellar protocols for arb opportunities.',
    initials:  'DP',
    publicKey: 'GCHPPYWSPXPAU7LK4WX5XVPKCVS3YFTPSQFJTTA6R4PPWHNVESZVHTL4',
  },
  {
    name:      'Shreya Nair',
    handle:    'shreya_n',
    role:      'Hedger',
    location:  'Mumbai, IN',
    bio:       'Analyst at a crypto fund. Uses on-chain options to hedge spot exposure and smooth out portfolio drawdowns.',
    initials:  'SN',
    publicKey: 'GCVE65B3HMCX75FQRXR7PK7SP2DPLH2XG6QMQHLGYXGS43PZ2HDAH5PN',
  },
  {
    name:      'Rahul Verma',
    handle:    'rahulv',
    role:      'Options Writer',
    location:  'Pune, IN',
    bio:       'Long-time Stellar community member. Writes covered calls for yield and follows IV closely across DeFi options protocols.',
    initials:  'RV',
    publicKey: 'GAVRQTKQ7VXJMBJKHZYK7BRI5OCJDPR26WKSDMR7JEM2WWXZI4ZPPT4L',
  },

  // ── Batch 2 (Black Belt onboarding — 24 additional users) ──────────
  {
    name:      'Aditi Krishnan',
    handle:    'aditi_k_91',
    role:      'Options Trader',
    location:  'Hyderabad, IN',
    bio:       'Quant at a desk in Hitech City. Backtests Strix premiums vs. Deribit on weekends. Mostly lurks.',
    initials:  'AK',
    publicKey: 'GCLI66S56HCNDVD6RJH7TEDVDSSMM6L2TNHSDV75JZUVLBSKSUH6NWV4',
  },
  {
    name:      'Vikram Joshi',
    handle:    'vikj.eth',
    role:      'Arbitrageur',
    location:  'Pune, IN',
    bio:       'Arb bots on 3 chains. Stellar latency is wild. Looking for parity gaps.',
    initials:  'VJ',
    publicKey: 'GDZWQMLO75C5LP5DTFN4W4MPZMA6673PJL5JVTHP5ZNUGT77RZE2X7QI',
  },
  {
    name:      'Sneha Kapoor',
    handle:    'sk0x',
    role:      'LP / Yield',
    location:  'Gurugram',
    bio:       'farmoor 🌾 done with pendle, here for the real APR not the screenshots',
    initials:  'SK',
    publicKey: 'GDUZ6S6TL3VMFCSXRDM75YCMTFPQCKBGDUVHXRZQNDXHWRIFF67HBGIE',
  },
  {
    name:      'Arjun Reddy',
    handle:    'arjr_xlm',
    role:      'Options Writer',
    location:  'Hyderabad, IN',
    bio:       'Stellar bag since 2018 ICO. Writing covered calls feels less degenerate than perps. Probably.',
    initials:  'AR',
    publicKey: 'GA7SUV5MU2IMMHAZ6UGED636LN26YSWAH5VRKXHDDGDCZFLH5LIK7BEB',
  },
  {
    name:      'Pooja Gupta',
    handle:    'poojaG',
    role:      'Hedger',
    location:  'BLR',
    bio:       'Treasury at a small Web3 startup. Trying puts so I don\'t have to explain another -40% quarter.',
    initials:  'PG',
    publicKey: 'GD6DJIL2SKN2U66GIBYCIXHZPG3SLQ5KJRWWJ4AEGVPP5S4PMFRXAGFC',
  },
  {
    name:      'anonxlm.42',
    handle:    'anonxlm42',
    role:      'Options Trader',
    location:  '—',
    bio:       'no doxx. trading XLM weeklies. dm closed.',
    initials:  'AX',
    publicKey: 'GA36DAJR4EHYQF2FGPW2NX72HH2LT6GU5ZS7YBYMWAQPKPC7ZFT4NDXY',
  },
  {
    name:      'Meera Pillai',
    handle:    'meera_p',
    role:      'LP (small)',
    location:  'Kochi',
    bio:       'CA, retired. Son set up the wallet for me. Put in 50 USDC to see how it works. Earned 0.3 USDC, will report back.',
    initials:  'MP',
    publicKey: 'GCSPBRKQW5GGC3AZNHQPSFPLTAQFC76TLBKBRO4CYLWRV7SRSLX25WXY',
  },
  {
    name:      'Sahil Desai',
    handle:    'sahilmm',
    role:      'Market Maker',
    location:  'Surat',
    bio:       'building an MM stack for soroban dexes. waitlist open ↗',
    initials:  'SD',
    publicKey: 'GARK776E77FIHAJ5CBPJHLKYOPKKKRU3PM7RPIN3W5WLKHZIT2HN7OQA',
  },
  {
    name:      'Lukas M.',
    handle:    'lukas_opts',
    role:      'Options Trader',
    location:  'Berlin',
    bio:       'Ex-Frankfurt options desk. Got nuked in 2022, came back for IV. Strix premiums actually make sense, surprised tbh.',
    initials:  'LM',
    publicKey: 'GCGMT76LN4DMT3Z7YOXWL4XAJK46K5JSPHI4GR2Y72BLP66G3XRBJQNB',
  },
  {
    name:      'Elena Rossi',
    handle:    'elena.r',
    role:      'Hedger',
    location:  'Milan',
    bio:       'Risk PM at a fund (not the famous one). Testing on-chain puts for the discretionary side. Compliance is fun.',
    initials:  'ER',
    publicKey: 'GDDFWS7HTL77AKSZBL72DYMSGZICAXMPSBJGIV4IBJF6UEOIYPHBSX7E',
  },
  {
    name:      'tomás',
    handle:    'tomas_lp',
    role:      'LP',
    location:  'Lisbon',
    bio:       '2020 cohort. lost ~half in luna, didn\'t learn. ~20% allocation to underwriting now.',
    initials:  'TS',
    publicKey: 'GB4IDTSY55ZUMQIYA3W3EFWSJD5JL2RGPYCYWUWT2G6DO53ZCFMPDCSB',
  },
  {
    name:      'Maja Nowak',
    handle:    'maja_parity',
    role:      'Arbitrageur',
    location:  'Warsaw',
    bio:       'PhD in mathfin. Side project: scanning put-call parity gaps. So far Strix is tight. Annoying.',
    initials:  'MN',
    publicKey: 'GADOJPJP7R7WWI6HA5LJD57C5HTTGDPKD232FS6LUSE4BK75T7UMNZQH',
  },
  {
    name:      'Henrik A.',
    handle:    'henrik_eth',
    role:      'Options Writer',
    location:  'CPH',
    bio:       'building a retail options thing on the side. depositing here to see what a real vault model feels like.',
    initials:  'HA',
    publicKey: 'GA2VFW2CAKLMHYGGT24SX6EONEW6ZD5G5GMI3SLBHF7SK5TT4YRBLDBI',
  },
  {
    name:      'Sofia García',
    handle:    'sofig_mm',
    role:      'Market Maker',
    location:  'Madrid',
    bio:       'co-founder, MM shop. mostly SOL/EVM, evaluating soroban. happy to be early LP if quoting works.',
    initials:  'SG',
    publicKey: 'GBUZ5DUPXFZYS4QKLBYDYZQ5BRYNSWBWUKQWUUHV2WTHMJ6PONOCRMTV',
  },
  {
    name:      'Marcus R.',
    handle:    'marcus_cboe',
    role:      'Options Trader',
    location:  'NYC',
    bio:       'ex-CBOE pit. now I watch IV skew on Discord. life comes at you fast.',
    initials:  'MR',
    publicKey: 'GB7FXPY2I43TFS25RAZWCGRUXZXVP2E6R2CC4UIYYBBS3V3MOLYHZ542',
  },
  {
    name:      'Jenna Cole',
    handle:    'jenna_dao',
    role:      'Liquidity Provider',
    location:  'SF',
    bio:       'CFO for a DAO. We\'re looking at sustainable yield for the treasury. Premium income beats farming inflation.',
    initials:  'JC',
    publicKey: 'GBII3ZW42QGOZEU4TRS2GTEX7NQISLDQLBYKBZ4HIM4F3UMFYDGU4IL4',
  },
  {
    name:      'Diego H.',
    handle:    'diego.eth',
    role:      'Arbitrageur',
    location:  'CDMX',
    bio:       'bridging xlm <> eth all day. arb thin but consistent. options is the new thing I\'m looking at.',
    initials:  'DH',
    publicKey: 'GAWQEEWZDBMDTA35FDOQLOEQ5VLMD7BH5TL6SWVQ6X7ZEEGO2BGO4RDL',
  },
  {
    name:      'Caroline M.',
    handle:    'cmartin_risk',
    role:      'Hedger',
    location:  'Toronto',
    bio:       'risk at a CEX (no, not that one). researching 3rd-party hedge venues for house book offsets. early days.',
    initials:  'CM',
    publicKey: 'GDVAJ6NPDHVSMCPBRC2FOEDVLEW7UEUAHPVC3ZD5ETLAYDPTKHFCIW5D',
  },
  {
    name:      'Lucas Oliveira',
    handle:    'lucasolv_br',
    role:      'Options Writer',
    location:  'SP',
    bio:       'stellar BR community. covered calls content for my newsletter. 2400 subs, growing.',
    initials:  'LO',
    publicKey: 'GBUZVKELRXGX4KPIEOLGPS7DJ5BIUD7LNRJ43EVYPRTL5TYUMOZJ53BH',
  },
  {
    name:      'Hiro T.',
    handle:    'hiro_t.eth',
    role:      'Options Trader',
    location:  'Tokyo',
    bio:       '元・野村デリバ. soroban project watcher on JP crypto twitter. follow for nothing in particular.',
    initials:  'HT',
    publicKey: 'GBUSK4RJKDFCVJHTAFTS6HGUR5YK3FB3VFUCUFEQ6FWJEU5Z5TTL2EJE',
  },
  {
    name:      'Min-Jun Park',
    handle:    'mjp_kr',
    role:      'Market Maker',
    location:  'Seoul',
    bio:       'eng at a korean exchange. evaluating strix for institutional MM. not financial advice etc.',
    initials:  'MJ',
    publicKey: 'GBVUBLMSCXSVM3I7COWOBFQXBUJPGU4EE5WRG4SZWUHMZUBVUKB6YJ4A',
  },
  {
    name:      'wei',
    handle:    'wei_lowfreq',
    role:      'Arbitrageur',
    location:  'SG',
    bio:       'HFT day job. options arb as a hobby because it\'s slow. mostly winning, occasionally not.',
    initials:  'WC',
    publicKey: 'GC7CDKGWND2J3AKEPNNZ2JDCIODJDHDKQXJVSNRQ6W4PRBVEI6IBOMO7',
  },
  {
    name:      'Priya A.',
    handle:    'priya_writes',
    role:      'LP / educator',
    location:  'Sydney',
    bio:       'australia defi newsletter ↗ documenting the strix experience as I LP. real numbers, real losses if it happens.',
    initials:  'PA',
    publicKey: 'GAFL5KTCBR3ATLU77QEE4ZB2CAZLRHML2IHE3VRISS5UJWNZOFZMV47F',
  },
  {
    name:      'Yusuf A.',
    handle:    'yusuf_yield',
    role:      'Options Writer',
    location:  'DXB',
    bio:       'family office allocator. small piece into DeFi yield experiments. mostly conservative covered calls.',
    initials:  'YA',
    publicKey: 'GCGVJYEMJG2IUV5QJS536N2HZYK32SOJ4SFTHWSAIRTA5XD7JROGWX6J',
  },
];

export const EXPLORER_URL = 'https://stellar.expert/explorer/testnet/account';
