export interface CommunityAccount {
  name:      string;
  handle:    string;
  role:      string;
  location:  string;
  bio:       string;
  initials:  string;
  publicKey: string;
}

export const COMMUNITY_ACCOUNTS: CommunityAccount[] = [
  {
    name:      'Rohan Sharma',
    handle:    'rohan_s',
    role:      'Options Trader',
    location:  'Bangalore, IN',
    bio:       'SDE-2 by day, DeFi degenerate by night. Trades vol across protocols — found Strix through the Stellar Discord.',
    initials:  'RS',
    publicKey: 'GCSM3UOWL2H27WV6F63J6INHVYUKNRDHCRDZKVAW3NU6FNRQSZNNLGSW',
  },
  {
    name:      'Ananya Iyer',
    handle:    'ananyai',
    role:      'Liquidity Provider',
    location:  'Chennai, IN',
    bio:       'Into passive yield strategies. Allocates a portion of her crypto portfolio to DeFi vaults every month.',
    initials:  'AI',
    publicKey: 'GBMNYAW4EVLJEPI4SXNAIIW7R3XOCMRM5WMILW7MTIBADKS37SDHPGP4',
  },
  {
    name:      'Karan Malhotra',
    handle:    'karan_m',
    role:      'Market Maker',
    location:  'Delhi, IN',
    bio:       'Runs market-making scripts on a few Stellar DEX pairs. Here to see how on-chain options liquidity behaves.',
    initials:  'KM',
    publicKey: 'GCZLB4XUSS3A2K7Z6Y6D6P53EYLKDLAXWBTICCDYEPXRYOS2MAJRV2C2',
  },
  {
    name:      'Dev Patel',
    handle:    'devp_xyz',
    role:      'Arbitrageur',
    location:  'Ahmedabad, IN',
    bio:       'Blockchain developer with a thing for price inefficiencies. Monitors multiple Stellar protocols for arb opportunities.',
    initials:  'DP',
    publicKey: 'GCHPPYWSPXPAU7LK4WX5XVPKCVS3YFTPSQFJTTA6R4PPWHNVESZVHTL4',
  },
  {
    name:      'Shreya Nair',
    handle:    'shreya_n',
    role:      'Hedger',
    location:  'Mumbai, IN',
    bio:       'Analyst at a crypto fund. Uses on-chain options to hedge spot exposure and smooth out portfolio drawdowns.',
    initials:  'SN',
    publicKey: 'GCVE65B3HMCX75FQRXR7PK7SP2DPLH2XG6QMQHLGYXGS43PZ2HDAH5PN',
  },
  {
    name:      'Rahul Verma',
    handle:    'rahulv',
    role:      'Options Writer',
    location:  'Pune, IN',
    bio:       'Long-time Stellar community member. Writes covered calls for yield and follows IV closely across DeFi options protocols.',
    initials:  'RV',
    publicKey: 'GAVRQTKQ7VXJMBJKHZYK7BRI5OCJDPR26WKSDMR7JEM2WWXZI4ZPPT4L',
  },

  // ── Batch 2 (Black Belt onboarding — 24 additional users) ──────────
  {
    name:      'Aditi Krishnan',
    handle:    'aditik',
    role:      'Options Trader',
    location:  'Hyderabad, IN',
    bio:       'Quant analyst exploring on-chain options for systematic strategies. Compares Strix premiums against CEX desks.',
    initials:  'AK',
    publicKey: 'GCLI66S56HCNDVD6RJH7TEDVDSSMM6L2TNHSDV75JZUVLBSKSUH6NWV4',
  },
  {
    name:      'Vikram Joshi',
    handle:    'vikj_eth',
    role:      'Arbitrageur',
    location:  'Pune, IN',
    bio:       'Runs cross-protocol arb bots on Solana and Stellar. Watches put-call parity gaps for fast trades.',
    initials:  'VJ',
    publicKey: 'GDZWQMLO75C5LP5DTFN4W4MPZMA6673PJL5JVTHP5ZNUGT77RZE2X7QI',
  },
  {
    name:      'Sneha Kapoor',
    handle:    'sneha_k',
    role:      'Liquidity Provider',
    location:  'Gurugram, IN',
    bio:       'Yield farmer rotating capital across DeFi vaults. Tracks realized APR over claimed APY.',
    initials:  'SK',
    publicKey: 'GDUZ6S6TL3VMFCSXRDM75YCMTFPQCKBGDUVHXRZQNDXHWRIFF67HBGIE',
  },
  {
    name:      'Arjun Reddy',
    handle:    'arjr',
    role:      'Options Writer',
    location:  'Hyderabad, IN',
    bio:       'Underwrites covered calls passively for income. Long-time Stellar holder since 2019.',
    initials:  'AR',
    publicKey: 'GA7SUV5MU2IMMHAZ6UGED636LN26YSWAH5VRKXHDDGDCZFLH5LIK7BEB',
  },
  {
    name:      'Pooja Gupta',
    handle:    'pooja_g',
    role:      'Hedger',
    location:  'Bangalore, IN',
    bio:       'Treasury manager at a Web3 startup. Uses on-chain puts to hedge XLM holdings.',
    initials:  'PG',
    publicKey: 'GD6DJIL2SKN2U66GIBYCIXHZPG3SLQ5KJRWWJ4AEGVPP5S4PMFRXAGFC',
  },
  {
    name:      'Aryan Singh',
    handle:    'aryan_xlm',
    role:      'Options Trader',
    location:  'Noida, IN',
    bio:       'Trades XLM options around macro events. Active in Stellar Discord trading channels.',
    initials:  'AS',
    publicKey: 'GA36DAJR4EHYQF2FGPW2NX72HH2LT6GU5ZS7YBYMWAQPKPC7ZFT4NDXY',
  },
  {
    name:      'Meera Pillai',
    handle:    'meera_p',
    role:      'Liquidity Provider',
    location:  'Kochi, IN',
    bio:       'Retired CA, learning DeFi. Started LPing small amounts to understand the mechanics first-hand.',
    initials:  'MP',
    publicKey: 'GCSPBRKQW5GGC3AZNHQPSFPLTAQFC76TLBKBRO4CYLWRV7SRSLX25WXY',
  },
  {
    name:      'Sahil Desai',
    handle:    'sahild',
    role:      'Market Maker',
    location:  'Surat, IN',
    bio:       'Runs an MM startup focused on emerging-chain DEX pairs. Stellar is next on the integration list.',
    initials:  'SD',
    publicKey: 'GARK776E77FIHAJ5CBPJHLKYOPKKKRU3PM7RPIN3W5WLKHZIT2HN7OQA',
  },
  {
    name:      'Lukas Müller',
    handle:    'lukasm',
    role:      'Options Trader',
    location:  'Berlin, DE',
    bio:       'Former equities options trader in Frankfurt, now full-time crypto. Built early bots on Bitfinex.',
    initials:  'LM',
    publicKey: 'GCGMT76LN4DMT3Z7YOXWL4XAJK46K5JSPHI4GR2Y72BLP66G3XRBJQNB',
  },
  {
    name:      'Elena Rossi',
    handle:    'elenar',
    role:      'Hedger',
    location:  'Milan, IT',
    bio:       'PM at a multi-strat crypto fund. Tests on-chain derivatives for fund-level downside protection.',
    initials:  'ER',
    publicKey: 'GDDFWS7HTL77AKSZBL72DYMSGZICAXMPSBJGIV4IBJF6UEOIYPHBSX7E',
  },
  {
    name:      'Tomás Silva',
    handle:    'tomasilva',
    role:      'Liquidity Provider',
    location:  'Lisbon, PT',
    bio:       'Bootstrap DeFi LP since 2020. Allocates 20% of his portfolio to underwriting vaults.',
    initials:  'TS',
    publicKey: 'GB4IDTSY55ZUMQIYA3W3EFWSJD5JL2RGPYCYWUWT2G6DO53ZCFMPDCSB',
  },
  {
    name:      'Maja Nowak',
    handle:    'majan',
    role:      'Arbitrageur',
    location:  'Warsaw, PL',
    bio:       'Ph.D student in mathematical finance. Spots and trades put-call parity arbs as a side project.',
    initials:  'MN',
    publicKey: 'GADOJPJP7R7WWI6HA5LJD57C5HTTGDPKD232FS6LUSE4BK75T7UMNZQH',
  },
  {
    name:      'Henrik Andersen',
    handle:    'henrika',
    role:      'Options Writer',
    location:  'Copenhagen, DK',
    bio:       'Engineer building options strategies for retail. Vault depositor exploring underwriting yields.',
    initials:  'HA',
    publicKey: 'GA2VFW2CAKLMHYGGT24SX6EONEW6ZD5G5GMI3SLBHF7SK5TT4YRBLDBI',
  },
  {
    name:      'Sofia García',
    handle:    'sofiag',
    role:      'Market Maker',
    location:  'Madrid, ES',
    bio:       'Co-founder of an MM firm on Solana and Stellar. Interested in being early LP on new options venues.',
    initials:  'SG',
    publicKey: 'GBUZ5DUPXFZYS4QKLBYDYZQ5BRYNSWBWUKQWUUHV2WTHMJ6PONOCRMTV',
  },
  {
    name:      'Marcus Reyes',
    handle:    'marcusr',
    role:      'Options Trader',
    location:  'New York, US',
    bio:       'Ex-CBOE options market maker now in crypto. Watches IV skew across on-chain options venues.',
    initials:  'MR',
    publicKey: 'GB7FXPY2I43TFS25RAZWCGRUXZXVP2E6R2CC4UIYYBBS3V3MOLYHZ542',
  },
  {
    name:      'Jenna Cole',
    handle:    'jennac',
    role:      'Liquidity Provider',
    location:  'San Francisco, US',
    bio:       'Crypto-native CFO at a DAO. Deploys treasury into underwriting vaults for diversified yield.',
    initials:  'JC',
    publicKey: 'GBII3ZW42QGOZEU4TRS2GTEX7NQISLDQLBYKBZ4HIM4F3UMFYDGU4IL4',
  },
  {
    name:      'Diego Hernández',
    handle:    'diegoh',
    role:      'Arbitrageur',
    location:  'Mexico City, MX',
    bio:       'Latin America DeFi power user. Bridges flows across Stellar and Ethereum for arb opportunities.',
    initials:  'DH',
    publicKey: 'GAWQEEWZDBMDTA35FDOQLOEQ5VLMD7BH5TL6SWVQ6X7ZEEGO2BGO4RDL',
  },
  {
    name:      'Caroline Martin',
    handle:    'carolinem',
    role:      'Hedger',
    location:  'Toronto, CA',
    bio:       'Risk manager at a crypto exchange. Uses third-party options venues to hedge house book exposure.',
    initials:  'CM',
    publicKey: 'GDVAJ6NPDHVSMCPBRC2FOEDVLEW7UEUAHPVC3ZD5ETLAYDPTKHFCIW5D',
  },
  {
    name:      'Lucas Oliveira',
    handle:    'lucasolv',
    role:      'Options Writer',
    location:  'São Paulo, BR',
    bio:       'Stellar Brazil ambassador. Writes covered calls as part of a retail-oriented yield content series.',
    initials:  'LO',
    publicKey: 'GBUZVKELRXGX4KPIEOLGPS7DJ5BIUD7LNRJ43EVYPRTL5TYUMOZJ53BH',
  },
  {
    name:      'Hiro Tanaka',
    handle:    'hirot',
    role:      'Options Trader',
    location:  'Tokyo, JP',
    bio:       'Former Nomura derivatives desk. Active on Japanese crypto Twitter, follows new Soroban projects closely.',
    initials:  'HT',
    publicKey: 'GBUSK4RJKDFCVJHTAFTS6HGUR5YK3FB3VFUCUFEQ6FWJEU5Z5TTL2EJE',
  },
  {
    name:      'Min-Jun Park',
    handle:    'minjunp',
    role:      'Market Maker',
    location:  'Seoul, KR',
    bio:       'Engineer at a Korean exchange MM team. Evaluates Strix for potential institutional market-making.',
    initials:  'MJ',
    publicKey: 'GBVUBLMSCXSVM3I7COWOBFQXBUJPGU4EE5WRG4SZWUHMZUBVUKB6YJ4A',
  },
  {
    name:      'Wei Chen',
    handle:    'weichen',
    role:      'Arbitrageur',
    location:  'Singapore, SG',
    bio:       'Builds high-frequency arb infra. Tracks options mispricing as a low-frequency strategy.',
    initials:  'WC',
    publicKey: 'GC7CDKGWND2J3AKEPNNZ2JDCIODJDHDKQXJVSNRQ6W4PRBVEI6IBOMO7',
  },
  {
    name:      'Priya Anand',
    handle:    'priyaa_xlm',
    role:      'Liquidity Provider',
    location:  'Sydney, AU',
    bio:       'Australian DeFi educator. Vault LP since beta, documents the experience for her newsletter readers.',
    initials:  'PA',
    publicKey: 'GAFL5KTCBR3ATLU77QEE4ZB2CAZLRHML2IHE3VRISS5UJWNZOFZMV47F',
  },
  {
    name:      'Yusuf Ahmed',
    handle:    'yusufa',
    role:      'Options Writer',
    location:  'Dubai, AE',
    bio:       'Family office allocator interested in DeFi yields. Writes calls on a portion of long-term XLM holdings.',
    initials:  'YA',
    publicKey: 'GCGVJYEMJG2IUV5QJS536N2HZYK32SOJ4SFTHWSAIRTA5XD7JROGWX6J',
  },
];

export const EXPLORER_URL = 'https://stellar.expert/explorer/testnet/account';
